{
 "title": "otus-user k8s",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "response codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(http_response_status{service=\"user-service\", http_response_status=~\"2.*|4.*|5.*\"}[2m]))) by (http_method,http_response_status)",
     "legendFormat": "{{http_response_status}}: {{http_endpoint}} ({{http_method}})"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(http_response_status{service=\"user-service\", http_response_status=~\"5.*\"}[2m]))) by (http_method)",
     "legendFormat": "{{http_response_status}}: {{http_endpoint}} ({{http_method}})"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_count{service=\"user-service\"}[2m])) by (http_method)",
     "legendFormat": "{{http_method}}"
    },
    {
     "expr": "sum(increase(http_response_time_seconds_count{service=\"user-service\"}[2m])) by (job)",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_time_seconds_bucket{service=\"user-service\",http_endpoint=~\"/user|/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_response_time_seconds_bucket{service=\"user-service\",http_endpoint=~\"/user|/user/.*\"}[2m])) by (le, job) )",
     "legendFormat": "{{http_method}}: P-90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{service=\"user-service\",http_endpoint=~\"/user|/user/.*\"}[2m])) by (le, job) )",
     "legendFormat": "{{http_method}}: P-99"
    }
   ]
  },
  {
   "title": "Create User latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"POST\", http_endpoint=~\"/user\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"POST\", http_endpoint=~\"/user\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"POST\", http_endpoint=~\"/user\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-99"
    }
   ]
  },
  {
   "title": "Create User RPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_count{service=\"user-service\", http_endpoint=\"/user\",http_method=\"POST\"}[2m])) by (http_method)",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Create User 5xx",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(http_response_status{service=\"user-service\", http_response_status=~\"5.*\", http_method=\"POST\", http_endpoint=\"/user\"}[2m]))) by (http_method)",
     "legendFormat": "{{http_response_status}}: {{http_endpoint}} ({{http_method}})"
    }
   ]
  },
  {
   "title": "Get User latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"GET\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"GET\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"GET\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-99"
    }
   ]
  },
  {
   "title": "Get User RPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_count{service=\"user-service\", http_endpoint=\"/user/*\",http_method=\"GET\"}[2m])) by (job)",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Get User 5xx",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(http_response_status{service=\"user-service\", http_response_status=~\"5.*\", http_method=\"GET\", http_endpoint=\"/user/*\"}[2m]))) by (http_method)",
     "legendFormat": "{{http_response_status}}: {{http_endpoint}} ({{http_method}})"
    }
   ]
  },
  {
   "title": "Update User latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"PUT\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"PUT\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"PUT\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-99"
    }
   ]
  },
  {
   "title": "Update User RPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_count{service=\"user-service\", http_endpoint=\"/user/*\",http_method=\"PUT\"}[2m])) by (job)",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Update User 5xx",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(http_response_status{service=\"user-service\", http_response_status=~\"5.*\", http_method=\"PUT\", http_endpoint=\"/user/*\"}[2m]))) by (http_method)",
     "legendFormat": "{{http_response_status}}: {{http_endpoint}} ({{http_method}})"
    }
   ]
  },
  {
   "title": "Delete User latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"DELETE\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"DELETE\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{service=\"user-service\", http_method=\"DELETE\", http_endpoint=~\"/user/.*\"}[2m])) by (le, job))",
     "legendFormat": "{{http_method}}: P-99"
    }
   ]
  },
  {
   "title": "Delete User RPC",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_count{service=\"user-service\", http_endpoint=\"/user/*\",http_method=\"DELETE\"}[2m])) by (job)",
     "legendFormat": "{{http_method}}"
    }
   ]
  },
  {
   "title": "Delete User 5xx",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(floor(increase(http_response_status{service=\"user-service\", http_response_status=~\"5.*\", http_method=\"DELETE\", http_endpoint=\"/user/*\"}[2m]))) by (http_method)",
     "legendFormat": "{{http_response_status}}: {{http_endpoint}} ({{http_method}})"
    }
   ]
  }
 ]
}