apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - name: postgres
          image: postgres:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_PASS
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: user-config-map
                  key: DB_NAME
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - name: postgres-pv-storage
              mountPath: /var/lib/postgresql/pg-data
